name: dsc-gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - wandb
  - pip
  - black
  - isort
  - flake8
  - matplotlib
  - networkx
  - seaborn
  - pandas
  - pip:
      - - requirements_cpu.txt
