name: dsc-gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.7
  - wandb
  - pip
  - black
  - isort
  - flake8
  - matplotlib
  - networkx
  - pip:
      - -r requirements_gpu.txt
