data_dir: "data"
batch_size_default: 32
num_cpus_default: 16
norm_features_default: true
test_datasets:
    - IMDB-BINARY
    - PROTEINS
    - ENZYMES
    - cora
    - citeseer
    - pubmed
graph:
    graph_data_name_default: IMDB-BINARY
    imdb_features: 135
node:
    node_data_name_default: cora
