early_stopping_patience_default: 5
early_stopping_min_delta_default: 0.001
max_epochs_default: 100
save_plots_dir: "figures/Chunk_256"

# Number of nodes whose influence distribution to plot after training GNN
n_nodes_influence: 1
